name:
  en: Zhihu Search
  zh-CN: 知乎搜索
description:
  en: Search questions and discussions on Zhihu.
  zh-CN: 在知乎搜索相关问题、高赞回答与专栏文章。
identifier: com.flyclip.extension.zhihu-search
icon: iconify:simple-icons:zhihu
actions:
  - title: 知乎
    url: https://www.zhihu.com/search?type=content&q=***
    requirements: [text]
