name:
  en: DuckDuckGo
  zh-CN: DuckDuckGo
description:
  en: Privacy search with DuckDuckGo.
  zh-CN: 使用 DuckDuckGo 隐私无追踪搜索引擎。
identifier: com.flyclip.extension.duckduckgo
icon: iconify:simple-icons:duckduckgo
actions:
  - title: DDG
    url: https://duckduckgo.com/?q=***
    requirements: [text]
