name:
  en: HTML Encode
  zh-CN: HTML 实体转义
description:
  en: Encode or decode HTML special character entities.
  zh-CN: HTML 特殊实体符号转义与反转义。
identifier: com.flyclip.extension.html-encode
icon: <&>
actions:
  - title: HTML 转义
    identifier: encode
    javascript: |
      return flyclip.input.text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
    requirements: [text]
    after: paste-result

  - title: HTML 反转义
    identifier: decode
    javascript: |
      return flyclip.input.text
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#039;/g, "'")
        .replace(/&#39;/g, "'");
    requirements: [text]
    after: paste-result
