name:
  en: URL Encode
  zh-CN: URL 编解码
description:
  en: Percent-encode and decode URL parameters.
  zh-CN: URL 百分号编码与反向解码。
identifier: com.flyclip.extension.url-encode
icon: "%20"
actions:
  - title: URL 编码
    identifier: encode
    javascript: return encodeURIComponent(flyclip.input.text);
    requirements: [text]
    after: paste-result

  - title: URL 解码
    identifier: decode
    javascript: |
      try {
        return decodeURIComponent(flyclip.input.text);
      } catch (e) {
        return flyclip.input.text;
      }
    requirements: [text]
    after: paste-result
