name:
  en: Douban Search
  zh-CN: 豆瓣搜索
description:
  en: Search movies, books, and music on Douban.
  zh-CN: 在豆瓣搜索高分电影、热门图书与音乐条目。
identifier: com.flyclip.extension.douban-search
icon: iconify:simple-icons:douban
options:
  - identifier: cat
    label:
      en: Category
      zh: 搜索分类
    type: multiple
    values:
      - "1001"
      - "1002"
      - "1003"
    value labels:
      - 电影 (Movie)
      - 图书 (Book)
      - 音乐 (Music)
    default value: "1001"

actions:
  - title: 豆瓣
    url: https://www.douban.com/search?cat={flyclip option cat}&q=***
    requirements: [text]
