name:
  en: JD Search
  zh-CN: 京东搜索
description:
  en: Search products on JD.com.
  zh-CN: 在京东商城搜索选中的商品与数码好物。
identifier: com.flyclip.extension.jd-search
icon: iconify:simple-icons:jd
actions:
  - title: 京东
    url: https://search.jd.com/Search?keyword=***
    requirements: [text]
