name:
  en: Claude
  zh-CN: Claude
description:
  en: Send selected text to Anthropic Claude AI.
  zh-CN: 发送选中文本给 Anthropic Claude 对话交互。
identifier: com.flyclip.extension.claude
icon: iconify:simple-icons:anthropic
actions:
  - title: Claude
    url: https://claude.ai/new?q=***
    requirements: [text]
