name:
  en: Taobao Search
  zh-CN: 淘宝搜索
description:
  en: Search items and deals on Taobao.
  zh-CN: 在淘宝网搜索选中的商品宝贝与优惠。
identifier: com.flyclip.extension.taobao-search
icon: iconify:simple-icons:taobao
actions:
  - title: 淘宝
    url: https://s.taobao.com/search?q=***
    requirements: [text]
