name:
  en: YouTube Search
  zh-CN: YouTube
description:
  en: Search videos on YouTube.
  zh-CN: 在 YouTube 上搜索全球精彩视频。
identifier: com.flyclip.extension.youtube-search
icon: iconify:simple-icons:youtube
actions:
  - title: YouTube
    url: https://www.youtube.com/results?search_query=***
    requirements: [text]
