name:
  en: Youdao Dictionary
  zh-CN: 有道词典
description:
  en: Look up words in Youdao Dictionary.
  zh-CN: 有道词典划词查词与权威翻译释义。
identifier: com.flyclip.extension.youdao-dict
icon: 有道
actions:
  - title: 有道词典
    url: https://dict.youdao.com/search?q={flyclip text}
    requirements: [text]
