name:
  en: Full/Half Width
  zh-CN: 全角半角转换
description:
  en: Convert between Full-width and Half-width characters.
  zh-CN: 全角标点字符与半角英文字符双向转换。
identifier: com.flyclip.extension.full-half-width
icon: 全半
actions:
  - title: 全角转半角 (Full to Half)
    identifier: to_half
    javascript: |
      let str = "";
      for (let i = 0; i < flyclip.input.text.length; i++) {
        let code = flyclip.input.text.charCodeAt(i);
        if (code === 12288) {
          str += String.fromCharCode(32);
        } else if (code >= 65281 && code <= 65374) {
          str += String.fromCharCode(code - 65248);
        } else {
          str += flyclip.input.text[i];
        }
      }
      return str;
    requirements: [text]
    after: paste-result

  - title: 半角转全角 (Half to Full)
    identifier: to_full
    javascript: |
      let str = "";
      for (let i = 0; i < flyclip.input.text.length; i++) {
        let code = flyclip.input.text.charCodeAt(i);
        if (code === 32) {
          str += String.fromCharCode(12288);
        } else if (code >= 33 && code <= 126) {
          str += String.fromCharCode(code + 65248);
        } else {
          str += flyclip.input.text[i];
        }
      }
      return str;
    requirements: [text]
    after: paste-result
