name:
  en: Bilibili Search
  zh-CN: 哔哩哔哩
description:
  en: Search anime, tutorials, and creators on Bilibili.
  zh-CN: 在哔哩哔哩搜索精选视频、教程与UP主。
identifier: com.flyclip.extension.bilibili-search
icon: iconify:simple-icons:bilibili
actions:
  - title: 哔哩哔哩
    url: https://search.bilibili.com/all?keyword=***
    requirements: [text]
