name:
  en: Remove Spaces
  zh-CN: 清除多余空格
description:
  en: Collapse duplicate spaces or strip all whitespace characters.
  zh-CN: 消除所有多余空格或压缩连续空白字符。
identifier: com.flyclip.extension.remove-spaces
icon: "␣"
actions:
  - title: 压缩空格
    identifier: collapse
    javascript: return flyclip.input.text.replace(/\s+/g, ' ').trim();
    requirements: [text]
    after: paste-result

  - title: 消除所有空格
    identifier: remove_all
    javascript: return flyclip.input.text.replace(/\s+/g, '');
    requirements: [text]
    after: paste-result
