name:
  en: IMDb
  zh-CN: IMDb 影视资料
description:
  en: Search movies, TV shows, and cast on IMDb.
  zh-CN: 在 IMDb 数据库搜索电影、剧集与演员资料。
identifier: com.flyclip.extension.imdb
icon: iconify:simple-icons:imdb
actions:
  - title: IMDb
    url: https://www.imdb.com/find?q=***
    requirements: [text]
