name:
  en: Amazon
  zh-CN: 亚马逊商城
description:
  en: Search Amazon worldwide with site selection.
  zh-CN: 在全球 Amazon 亚马逊商城（美/中/日/英/德）搜索商品。
identifier: com.flyclip.extension.amazon
icon: iconify:simple-icons:amazon
options:
  - identifier: site
    label:
      en: Amazon Store
      zh: 亚马逊商城站点
    type: multiple
    values:
      - amazon.com
      - amazon.cn
      - amazon.co.jp
      - amazon.co.uk
      - amazon.de
    value labels:
      - US (amazon.com)
      - 中国 (amazon.cn)
      - 日本 (amazon.co.jp)
      - 英国 (amazon.co.uk)
      - 德国 (amazon.de)
    default value: amazon.com

actions:
  - title: Amazon
    url: https://www.{flyclip option site}/s?k=***
    spaces as plus: true
    requirements: [text]
