name:
  en: IP Lookup
  zh-CN: IP 归属地查询
description:
  en: Query IP address geolocation and WHOIS info.
  zh-CN: 查询 IP 地址的地理位置、归属地与网络 ASN 信息。
identifier: com.flyclip.extension.ip-lookup
icon: IP
options:
  - identifier: provider
    label:
      en: Lookup Service
      zh: 查询平台
    type: multiple
    values:
      - ipinfo
      - ip138
      - bgp
    value labels:
      - IPInfo.io (Global)
      - IP138 (中国地区精准)
      - BGP Toolkit (HE.net ASN)
    default value: ipinfo

actions:
  - title: IP 查询
    identifier: lookup_ipinfo
    requirements: [text]
    url: https://ipinfo.io/{flyclip text}
