name:
  en: Baidu Search
  zh-CN: 百度搜索
description:
  en: Search with Baidu Search Engine.
  zh-CN: 使用百度搜索选中的关键词。
identifier: com.flyclip.extension.baidu-search
icon: iconify:simple-icons:baidu
actions:
  - title: 百度
    url: https://www.baidu.com/s?wd=***
    requirements: [text]
