name:
  en: Regex101
  zh-CN: Regex101 正则测试
description:
  en: Test and debug regular expressions in Regex101.
  zh-CN: 在 Regex101 中测试并分析正则表达式。
identifier: com.flyclip.extension.regex101
icon: ".*"
options:
  - identifier: flavor
    label:
      en: Regex Engine Flavor
      zh: 正则引擎分支
    type: multiple
    values:
      - pcre2
      - javascript
      - python
      - golang
      - rust
    value labels:
      - PCRE2
      - JavaScript
      - Python
      - Golang
      - Rust
    default value: pcre2

actions:
  - title: Regex101
    url: https://regex101.com/?regex={flyclip text}&flavor={flyclip option flavor}
    requirements: [text]
